version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocyclo
    - goconst
    - dupl
    - gocritic
    - gosec
    - nakedret
    - noctx
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - mnd
          - funlen
          - gocyclo
          - goconst
          - dupl
          - gosec
