name: Report a bug
description: Report a problem with the Yaak Proxy.
labels: "state:needs triage"
body:
  - type: markdown
    attributes:
      value: |
        Is this bug already reported? Upvote to get it noticed faster. [Here's the search](https://github.com/hanneshapke/yaak-proxy/issues). Upvote means giving it a :+1: reaction.

        Feature request? Please open in [discussions](https://github.com/hanneshapke/yaak-proxy/discussions/new/choose) instead.

        Just have a question or need support? Welcome to our [Slack Channel](http://tbd.tbd).
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction steps
      description: A step-by-step description of how to reproduce the bug from a **clean Yaak Proxy installation**. The more context you provide, the easier it is to find and fix the problem fast.
      placeholder: |
        1. Start Yaak Proxy
        2. Click X
    validations:
      required: true
  - type: textarea
    id: current_expected_behavior
    attributes:
      label: Current vs. Expected behavior
      description: |
        Current behavior (screenshots, videos, etc. are appreciated), vs. what you expected the behavior to be.

      placeholder: |
        Current behavior: <screenshot with an arrow> The proxy highlighted the word "He". Expected behavior: highlighting the name "Heidi".
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Yaak Proxy version and system specs
      description: |
        What are your system specifications
      placeholder: |
        Yaak Proxy: v0.1.10
        OS: macOS Tahoe 26.2
        Memory: 36 GiB
        Architecture: aarch64
    validations:
      required: true

  - type: textarea
    id: model_provider
    attributes:
      label: Model provider details
      placeholder: |
        - Provider: (Anthropic Claude, Google Gemini, OpenAI, etc.)
        - Model Name: (Claude Sonnet 4.5, Gemini 3 Pro, GPT-5)
    validations:
      required: true
