"""Vertex AI Pipelines definition for the Kiji PII model trainer.

Wraps the image built from ``model/Dockerfile`` — whose entrypoint is the
Metaflow flow ``model/flows/training_pipeline.py`` — as a single KFP step, and
compiles to the pipeline YAML that Vertex AI Pipelines consumes.

The flow is monolithic (export -> preprocess -> train -> evaluate -> ONNX ->
sign all run in one process), so it maps to one container step rather than one
step per stage. Splitting it would mean changing the flow, not the pipeline.
"""

# NOTE: no `from __future__ import annotations` here. KFP resolves component
# signatures at decoration time and cannot parse stringified annotations.
from kfp import dsl

# Published trainer image. Must be reachable from the Vertex AI worker pool:
# public on Docker Hub, or mirrored into Artifact Registry and referenced as
# <region>-docker.pkg.dev/<project>/<repo>/kiji-proxy:dev.
TRAINER_IMAGE = "575lab/kiji-proxy:dev"

# Matches the Dockerfile: WORKDIR /workspace, and training_config.toml paths are
# resolved relative to the working directory.
WORKSPACE = "/workspace"

# Hardcoded in training_pipeline.py (`exported_output = "model/quantized"`), so
# it cannot be redirected through the config file the way output_dir can.
CONTAINER_ONNX_DIR = f"{WORKSPACE}/model/quantized"

# Written to container-local disk, then copied to GCS once. Training directly
# against the gcsfuse mount is slow and trips over the checkpoint rename
# HuggingFace Trainer does between epochs.
CONTAINER_TRAINED_DIR = f"{WORKSPACE}/model/trained"


@dsl.component(base_image="python:3.13-slim")
def render_training_config(
    config_file: dsl.Output[dsl.Artifact],
    training_samples_uri: str,
    model_name: str,
    num_epochs: int,
    batch_size: int,
    learning_rate: float,
    warmup_steps: int,
    weight_decay: float,
    auxiliary_ce_loss_weight: float,
    bf16: bool,
    early_stopping_enabled: bool,
    early_stopping_patience: int,
    early_stopping_threshold: float,
    max_eval_samples: int,
    balanced_validation_split: bool,
    subsample_count: int,
    num_ai4privacy_samples: int,
    audit_allowlist_uri: str,
    skip_quantization: bool,
    skip_signing: bool,
    trained_dir: str,
) -> None:
    """Render training_config.toml from pipeline parameters.

    Emitting the config as its own artifact means the exact hyperparameters of a
    run are recorded in Vertex lineage, rather than being buried in a container
    command line.
    """

    def gcs_path(uri: str) -> str:
        """gs://bucket/key -> /gcs/bucket/key, the Vertex AI gcsfuse mount."""
        if uri.startswith("gs://"):
            return "/gcs/" + uri[len("gs://") :]
        return uri

    def toml_str(value: str) -> str:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    def toml_bool(value: bool) -> str:
        return "true" if value else "false"

    lines = [
        "# Generated by geap-pipelines-proxy. Do not edit by hand.",
        "",
        "[model]",
        f"name = {toml_str(model_name)}",
        "",
        "[training]",
        f"num_epochs = {num_epochs}",
        f"batch_size = {batch_size}",
        f"learning_rate = {learning_rate}",
        f"bf16 = {toml_bool(bf16)}",
        "torch_compile = false",
        f"warmup_steps = {warmup_steps}",
        f"weight_decay = {weight_decay}",
        f"auxiliary_ce_loss_weight = {auxiliary_ce_loss_weight}",
        f"max_eval_samples = {max_eval_samples}",
        f"balanced_validation_split = {toml_bool(balanced_validation_split)}",
        f"early_stopping_enabled = {toml_bool(early_stopping_enabled)}",
        f"early_stopping_patience = {early_stopping_patience}",
        f"early_stopping_threshold = {early_stopping_threshold}",
        "",
        "[paths]",
        f"training_samples_dir = {toml_str(gcs_path(training_samples_uri))}",
        f"output_dir = {toml_str(trained_dir)}",
        "",
        "[data]",
        f"subsample_count = {subsample_count}",
        f"num_ai4privacy_samples = {num_ai4privacy_samples}",
        f"audit_allowlist = {toml_str(gcs_path(audit_allowlist_uri))}",
        "",
        "[pipeline]",
        # Label Studio is not reachable from a Vertex worker pool; datasets are
        # staged to GCS ahead of the run instead.
        "skip_export = true",
        f"skip_quantization = {toml_bool(skip_quantization)}",
        f"skip_signing = {toml_bool(skip_signing)}",
        "",
    ]

    rendered = "\n".join(lines)
    print(rendered)
    with open(config_file.path, "w") as handle:
        handle.write(rendered)


@dsl.container_component
def train_pii_model(
    config_file: dsl.Input[dsl.Artifact],
    trained_model: dsl.Output[dsl.Model],
    onnx_model: dsl.Output[dsl.Model],
):
    """Run the Metaflow training flow, then publish its artifacts to GCS.

    ``command`` overrides the image ENTRYPOINT, so the flow is invoked
    explicitly. ``--config config-file <path>`` is Metaflow's syntax for
    supplying a value to ``Config("config-file", ...)``.
    """
    return dsl.ContainerSpec(
        image=TRAINER_IMAGE,
        command=["/bin/sh", "-ec"],
        args=[
            dsl.ConcatPlaceholder(
                [
                    'config="',
                    config_file.path,
                    '"\n',
                    'trained_out="',
                    trained_model.path,
                    '"\n',
                    'onnx_out="',
                    onnx_model.path,
                    '"\n',
                    "\n",
                    'cd "',
                    WORKSPACE,
                    '"\n',
                    'python model/flows/training_pipeline.py --config config-file "$config" run\n',
                    "\n",
                    "# The flow writes to container-local disk; publish to the\n",
                    "# gcsfuse-backed artifact paths once, at the end.\n",
                    'mkdir -p "$trained_out" "$onnx_out"\n',
                    'cp -R "',
                    CONTAINER_TRAINED_DIR,
                    '/." "$trained_out/"\n',
                    'if [ -d "',
                    CONTAINER_ONNX_DIR,
                    '" ]; then\n',
                    '  cp -R "',
                    CONTAINER_ONNX_DIR,
                    '/." "$onnx_out/"\n',
                    "else\n",
                    '  echo "no ONNX export produced at ',
                    CONTAINER_ONNX_DIR,
                    '" >&2\n',
                    "fi\n",
                ]
            )
        ],
    )


@dsl.pipeline(
    name="kiji-pii-model-training",
    description="Train, evaluate, export and sign the Kiji PII detection model.",
)
def kiji_training_pipeline(
    training_samples_uri: str,
    model_name: str = "microsoft/deberta-v3-base",
    num_epochs: int = 30,
    batch_size: int = 128,
    learning_rate: float = 2e-5,
    warmup_steps: int = 500,
    weight_decay: float = 0.01,
    auxiliary_ce_loss_weight: float = 0.2,
    bf16: bool = True,
    early_stopping_enabled: bool = True,
    early_stopping_patience: int = 3,
    early_stopping_threshold: float = 0.005,
    max_eval_samples: int = 0,
    balanced_validation_split: bool = True,
    subsample_count: int = 0,
    num_ai4privacy_samples: int = -1,
    audit_allowlist_uri: str = "",
    skip_quantization: bool = True,
    skip_signing: bool = False,
) -> None:
    """Defaults mirror model/flows/training_config.toml as committed."""
    config_task = render_training_config(
        training_samples_uri=training_samples_uri,
        model_name=model_name,
        num_epochs=num_epochs,
        batch_size=batch_size,
        learning_rate=learning_rate,
        warmup_steps=warmup_steps,
        weight_decay=weight_decay,
        auxiliary_ce_loss_weight=auxiliary_ce_loss_weight,
        bf16=bf16,
        early_stopping_enabled=early_stopping_enabled,
        early_stopping_patience=early_stopping_patience,
        early_stopping_threshold=early_stopping_threshold,
        max_eval_samples=max_eval_samples,
        balanced_validation_split=balanced_validation_split,
        subsample_count=subsample_count,
        num_ai4privacy_samples=num_ai4privacy_samples,
        audit_allowlist_uri=audit_allowlist_uri,
        skip_quantization=skip_quantization,
        skip_signing=skip_signing,
        trained_dir=CONTAINER_TRAINED_DIR,
    )
    config_task.set_display_name("render-training-config")
    config_task.set_caching_options(False)

    train_task = train_pii_model(config_file=config_task.outputs["config_file"])
    train_task.set_display_name("train-pii-model")
    train_task.set_caching_options(False)

    # bf16 in the committed config requires Ampere or newer. A100 40GB is the
    # smallest Vertex accelerator that satisfies that at batch_size 128.
    train_task.set_accelerator_type("NVIDIA_TESLA_A100")
    train_task.set_accelerator_limit(1)
    train_task.set_cpu_limit("12")
    train_task.set_memory_limit("85G")

    train_task.set_env_variable("TOKENIZERS_PARALLELISM", "false")
    # Gated Hugging Face datasets need HF_TOKEN. Deliberately not set here: an
    # empty value reads as a malformed credential rather than "no token". Inject
    # it at submit time, or via Secret Manager, only if you need gated data.


def compile_pipeline(output_path: str = "kiji_training_pipeline.yaml") -> str:
    """Compile the pipeline to the YAML Vertex AI Pipelines consumes."""
    from kfp import compiler

    compiler.Compiler().compile(
        pipeline_func=kiji_training_pipeline,
        package_path=output_path,
    )
    return output_path
